version: '3.7'
services:
  web:
    image: nsfw:latest
    deploy:  # This only takes effect when deploying to a swarm with docker stack deploy, and is ignored by docker-compose up and docker-compose run.
      mode: global
      resources:
        limits:
          cpus: "1"  # limiting each one to use, at most, 10 core of CPU
          memory: 1000M  # limiting each one to use, at most, 4096M of RAM
      restart_policy:
        condition: any # Immediately restart containers if one fails.
    ports:
      - 6739:6739
    volumes:
      - .:/filter-nsfw-python3  # mount
      - /root/CrawlerBackend/download/avatar:/root/CrawlerBackend/download/avatar  # mount
    command: flask run --host=0.0.0.0 --port=6739
